SYMS = %w(
  wait_frame
  draw_arrow
  draw_ruby
  play_sound
  pad_trigger
  btn_a_pressed
  show_title
  hide_title
).sort
#  play_music
#  stop_music

puts <<EOD
// Generated by gen_builtin_symbols.rb
#ifndef MRBC_SRC_AUTOGEN_BUILTIN_SYMBOL_H_
#define MRBC_SRC_AUTOGEN_BUILTIN_SYMBOL_H_
static const char *builtin_symbols[] = {
EOD
SYMS.each.with_index do |name, i|
  puts %!  "#{name}",  // MRBC_SYMID_#{name} = #{i}(0x#{i.to_s(16)})!
end
puts <<EOD
};
enum {
EOD
SYMS.each.with_index do |name, i|
  puts "  MRBC_SYMID_#{name} = #{i},"
end
puts <<EOD
};
#define MRBC_SYM(sym) MRBC_SYMID_##sym
#define OFFSET_BUILTIN_SYMBOL #{SYMS.size}
#endif
EOD
