;this file for FamiTone2 library generated by text2data tool

stage1_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $f0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cd,$cc,$c8,$c5,$c3,$c0,$00,$07
@env2:
	.byte $cf,$06,$ca,$c0,$00,$03


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $82,$32,$85,$33,$3b,$40,$85,$41,$3a,$81
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref1:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref2:
	.byte $80,$33,$32,$85,$33,$29,$28,$85,$28,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref3:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref4:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
